### ISSUE TITLE
How convert ?

### ISSUE THREAD

**Issue by inukaze** [sirconan/gdi-conversion#3]
Hi there, you know some tool let me convert from gdi to cue format ?
and/or another tool for convert cdi to bin (raw) format ?

**Comment by sirconan** [comment]
I don't know tools to do this type of conversion :confused:

**Comment by inukaze** [comment]
Thank for you answer, i found a way from convert gdi to chd.

Basically if you are under GNU/Linux . you can use chdman

```
ISO="ZeroGunner2(Japan).gdi"
CHD="ZeroGunner2(Japan).chd"
chdman createcd --input "$ISO" --output "$CHD"
```

> chdman - MAME Compressed Hunks of Data (CHD) manager 0.214 (unknown)
> Output CHD:   ZeroGunner2(Japan).chd
> Input file:   ZeroGunner2(Japan).gdi
> Input tracks: 3
> Input length: 122:02:00
> Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
> Logical size: 1,344,324,096
> Compression complete ... final ratio = 26.5% 

The content of files inside gdi (similar to cue, are text file too) need the names not have any Space in the name for skip faults. and well.

The unique thing i need to do now is convert cdi to bin/cue or directly to chd

**Comment by sirconan** [comment]
Thank you for your feedback and congrats for gdi to cue conversion with chdman :clap: 
I have already tested chdman for cue to gdi conversion but generated file didn't work on GDemu

**Comment by inukaze** [comment]
Well i hope someone can solve the load of CHD format on GDEmu because on some case can save a lot of file size, for example if i don't remember bad, Ikagura from 700 MB, if you compress with CHD, the new file size just is aprox 30 MB.

Well if you got information about how convert CDI to Bin+Cue or directly to CHD, post here please, because i want to try multiple compressions for determinate if better some compression format each game, or in general is good use for example chd or another one like ISZ
